### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3431-3432: character maps to <undefined>

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#10]
D:\Documents\writing\Archives>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1897904-The-dictaphone
### Now archiving 1897904-The-dictaphone
# 1897904-The-dictaphone: Gathering info.
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 40, in <module>
    args.func(args)
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 18, in get
    archive(id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 78, in archive
    barf(story_root + "outline.html",formatOutline(info.pretty_title,canon_descents,canon_names))
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 10, in barf
    o.write(text)
  File "C:\Users\linux\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3431-3432: character maps to <undefined>

**Comment by Ackater** [comment]
c11f5d8 should fix this. Windows doesn't default to utf-8, and I guess that outline had some different characters

**Comment by ProfHariSeldon** [comment]
That fixed it!  The whole thing is working for me now.

**Comment by Ackater** [comment]
Cool, let me know if you have any other issues or suggestions!
