### ISSUE TITLE
IndexError: list index out of range (again)

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#15]
I downloaded the most recent version of this and that did not solve this

D:\Documents\writing\Archives>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1897904-The-dictaphone
### Now archiving 1897904-The-dictaphone
# 1897904-The-dictaphone: Gathering info.
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 40, in <module>
    args.func(args)
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 18, in get
    archive(id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 77, in archive
    canon_descents, canon_names = get_chapter_list(story_id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\scraper.py", line 149, in get_chapter_list
    url_cutoff = outline_links[0].attrib['href'].rfind("/") + 1
IndexError: list index out of range

**Comment by Ackater** [comment]
Delete your session file, and login again.
