### ISSUE TITLE
ParserError config.yaml

### ISSUE THREAD

**Issue by SomeRandomDude870** [Ackater/writing.com-archival#41]
Hi, I get there an Parsererror.

``python archiver.py get 1884280-Girlfriends-Futanari-Secret
Traceback (most recent call last):
  File "D:\writing.com-archival\archiver.py", line 1, in <module>
    from scraper import get_story_info, get_outline, get_chapter, get_all_interactives_list, get_recent_chapters
  File "D:\writing.com-archival\scraper.py", line 13, in <module>
    from session import get_page, get_page_search
  File "D:\writing.com-archival\session.py", line 25, in <module>
    config_yaml = yaml.load(file, Loader=yaml.FullLoader)
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "config.yaml", line 7, column 1

**Comment by Ackater** [comment]
Looks like an issue with your config.yaml file?

**Comment by SomeRandomDude870** [comment]
No idea?

**Comment by Ackater** [comment]
Needs a space after the colon on line 7?
