### ISSUE TITLE
FilenotFoundError - nothing in index.html

### ISSUE THREAD

**Issue by SomeRandomDude870** [Ackater/writing.com-archival#42]
Hi, I get another Error.
Every chapter will be shown in the cmd and after the last I get this Error:

`Traceback (most recent call last):
  File "D:\writing.com-archival\run.py", line 46, in <module>
    args.func(args)
  File "D:\writing.com-archival\run.py", line 13, in get
    archive(id)
  File "D:\writing.com-archival\archiver.py", line 180, in archive
    o.write(formatIndex(dumps(story, indent=0, sort_keys=True, separators=(',',':'))))
  File "D:\writing.com-archival\htmlformat.py", line 2, in formatIndex
    with open('templates/index.html', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'templates/index.html'`

**Comment by SomeRandomDude870** [comment]
push?
