### ISSUE TITLE
ImportError: cannot import name request

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#5]
I pip installed mechanicalsoup, jinja2, and lxml.
I am running Windows.
I have Python 2.7.14 (Release Date: Sept. 16, 2017)
This is the error:

D:\Documents\writing\Archives\writing.com-archival-master>C:\Python27\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1258638
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 2, in <module>
    from archiver import archive, archive_search, update_archive, is_item_id
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 1, in <module>
    from scraper import get_chapter_list, get_search_ids
  File "D:\Documents\writing\Archives\writing.com-archival-master\scraper.py", line 1, in <module>
    from urllib import request
ImportError: cannot import name request

Also please let me know if I need to use a paid Writing.com account instead of a free Writing,com account after we fix this.

**Comment by Ackater** [comment]
Sorry, this script requires Python3.

I am using a free account, the script automatically retries if it encounters an error
