### ISSUE TITLE
defs.ServerRefusal: Heavy Server Volume

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#9]
Can I really download 5187 chapters on a free Writing.com account?

This is an interactive story containing 5187 chapters:

D:\Documents\writing\Archives>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1897904-The-dictaphone
### Now archiving 1897904-The-dictaphone
# 1897904-The-dictaphone: Gathering info.
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 40, in <module>
    args.func(args)
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 18, in get
    archive(id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 77, in archive
    canon_descents, canon_names = get_chapter_list(story_id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\scraper.py", line 103, in get_chapter_list
    assertNotServerRefusal(outline)
  File "D:\Documents\writing\Archives\writing.com-archival-master\scraper.py", line 47, in assertNotServerRefusal
    raise ServerRefusal('Heavy Server Volume')
defs.ServerRefusal: Heavy Server Volume

**Comment by Ackater** [comment]
Yes. Please try until it starts downloading. The initial outline downloading does not automatically retry. I will fix this in the future
